services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - 1883:1883
    volumes:
      - ./mqtt/config/:/mosquitto/config/
      - ./mqtt/data:/mosquitto/data
    restart: unless-stopped

  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - 1880:1880
    volumes:
      - ./nodered/data:/data
    environment:
      - TZ=Europe/Paris
    restart: unless-stopped
  
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - db/.env
    restart: unless-stopped